<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-EOAIVF8" failures="1" tests="14" name="Default test" time="9.889" errors="0" timestamp="17 Jun 2020 10:33:10 GMT">
  <testcase classname="TC02_GETRequest" name="getHeader" time="2.988"/>
  <testcase classname="TC05_GETUniqueLanguage" name="SingleLanguage" time="0.967"/>
  <testcase classname="ExcelSheet" name="trail" time="1.237"/>
  <testcase classname="temp" name="trycry" time="0.33">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at temp.trycry(temp.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- trycry -->
  <testcase classname="com.paytm.qa.testcases.TC004_UniqueLanguage" name="verifyUniqueLanguage" time="0.328"/>
  <testcase classname="com.paytm.qa.testcases.TC005_printMovieNamesInExcel" name="writeMovieNamesinExcel" time="0.923"/>
  <testcase classname="com.paytm.qa.testcases.TC001_GETStatusCode" name="verifyStatusDetails" time="0.32"/>
  <testcase classname="TC04_GET_MovieCode" name="movieCodeTest" time="0.387"/>
  <testcase classname="com.paytm.qa.testcases.TC002_MoviePosterURL" name="verifyMoviePosterURL" time="0.377"/>
  <testcase classname="com.paytm.qa.testcases.TC003_UniqueMovieCode" name="verifyUniqueMovieCode" time="0.366"/>
  <testcase classname="trail" name="atrywith" time="0.734"/>
  <testcase classname="TC01_GET_Request" name="getWeatherDetails" time="0.252"/>
  <testcase classname="TC03_GETResponseBody" name="jsonResponseBody" time="0.406"/>
  <testcase classname="ExcelSheet" name="trail" time="0.144"/>
</testsuite> <!-- Default test -->
